using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace SimpleRepaintCache
{
    /// <summary>
    /// Generates optimized MM patch files from part analysis results
    /// </summary>
    public static class PatchGenerator
    {
        /// <summary>
        /// Sanitizes a part name for use in MM @PART[] syntax.
        /// MM does not support spaces in part names - replace with '?'
        /// </summary>
        private static string SanitizePartName(string partName)
        {
            return partName.Replace(' ', '?');
        }

        /// <summary>
        /// Generates the complete cache patch file content
        /// </summary>
        public static string GeneratePatch(List<PartAnalyzer.PartAnalysis> analyses, List<ColorEntry> colors, RepaintSettings settings)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by SimpleRepaintCache");
            sb.AppendLine("// This file replaces the original SimpleRepaint.cfg for faster loading");
            sb.AppendLine("// Generated at: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            sb.AppendLine();

            // Get only used colors (skip NOT_USED)
            var usedColors = colors.FindAll(c => c.IsUsed);

            if (usedColors.Count == 0)
            {
                UnityEngine.Debug.LogError("[SimpleRepaintCache] No valid colors found! Cannot generate patch.");
                return string.Empty;
            }

            UnityEngine.Debug.Log($"[SimpleRepaintCache] Generating patch with {usedColors.Count} colors for {analyses.Count} parts...");

            foreach (var analysis in analyses)
            {
                if (!analysis.ShouldInject) continue;

                if (analysis.UseB9PS)
                {
                    GenerateB9PSPatch(sb, analysis, usedColors, settings);
                }
                else
                {
                    GeneratePartVariantsPatch(sb, analysis, usedColors, settings);
                }
            }

            // Add cleanup section
            sb.AppendLine();
            sb.AppendLine("// ===================================================================");
            sb.AppendLine("// Clean-up (same as original SimpleRepaint.cfg)");
            sb.AppendLine("// ===================================================================");
            sb.AppendLine("@PART[*]:HAS[#SR_RepaintType[*]]:AFTER[zzzzzzSimpleRepaint]");
            sb.AppendLine("{");
            sb.AppendLine("\t!SR_Ignore = DELETE");
            sb.AppendLine("\t!SR_RepaintType = DELETE");
            sb.AppendLine("\t!SR_MaterialMask1 = DELETE");
            sb.AppendLine("}");
            sb.AppendLine("@PART[*]:HAS[#SR_Ignore[*]]:AFTER[zzzzzzSimpleRepaint]");
            sb.AppendLine("{");
            sb.AppendLine("\t!SR_Ignore = DELETE");
            sb.AppendLine("}");
            sb.AppendLine("@PART[*]:HAS[#SR_UsePartVariant[*]]:AFTER[zzzzzzSimpleRepaint]");
            sb.AppendLine("{");
            sb.AppendLine("\t!SR_UsePartVariant = DELETE");
            sb.AppendLine("}");
            sb.AppendLine("@PART[*]:HAS[#SR_WhitelistOnly[*]]:AFTER[zzzzzzSimpleRepaint]");
            sb.AppendLine("{");
            sb.AppendLine("\t!SR_WhitelistOnly = DELETE");
            sb.AppendLine("}");
            sb.AppendLine("@PART[*]:HAS[#SR_Whitelisted[*]]:AFTER[zzzzzzSimpleRepaint]");
            sb.AppendLine("{");
            sb.AppendLine("\t!SR_Whitelisted = DELETE");
            sb.AppendLine("}");

            // KerbalEVA cleanup
            sb.AppendLine("@PART[kerbalEVA*]:HAS[@MODULE[ModuleB9PartSwitch]:HAS[#moduleID[SimpleRepaint]]]:AFTER[zzzzzzSimpleRepaint]");
            sb.AppendLine("{");
            sb.AppendLine("\t!MODULE[ModuleB9PartSwitch]:HAS[#moduleID[SimpleRepaint]] {}");
            sb.AppendLine("\t!SR_Ignore = DELETE");
            sb.AppendLine("\t!SR_RepaintType = DELETE");
            sb.AppendLine("\t!SR_MaterialMask1 = DELETE");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void GenerateB9PSPatch(StringBuilder sb, PartAnalyzer.PartAnalysis analysis, List<ColorEntry> colors, RepaintSettings settings)
        {
            string partName = SanitizePartName(analysis.PartName);
            string materialMask = analysis.MaterialMask;

            sb.AppendLine($"@PART[{partName}]:FINAL");
            sb.AppendLine("{");
            sb.AppendLine("\t%SR_RepaintType = B9PS");
            sb.AppendLine($"\t%SR_MaterialMask1 = {materialMask}");
            sb.AppendLine();
            sb.AppendLine("\tMODULE");
            sb.AppendLine("\t{");
            sb.AppendLine("\t\tname = ModuleB9PartSwitch");
            sb.AppendLine("\t\tmoduleID = SimpleRepaint");
            sb.AppendLine("\t\tswitcherDescription = #LOC_SR_ColorVariant_title");
            sb.AppendLine("\t\taffectDragCubes = false");
            sb.AppendLine("\t\taffectFARVoxels = false");
            sb.AppendLine($"\t\tswitchInFlight = {(settings.RepaintInFlight ? "true" : "false")}");
            sb.AppendLine("\t\tuiGroupName = SimpleRepaint");
            sb.AppendLine("\t\tuiGroupDisplayName = #LOC_SR_Repaint_UIGroup_title");
            sb.AppendLine();

            // Original subtype
            sb.AppendLine("\t\tSUBTYPE");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\tname = SR_Original");
            sb.AppendLine("\t\t\ttitle = #LOC_SR_Color_Original");
            sb.AppendLine("\t\t\tprimaryColor = #C7C7C7");
            sb.AppendLine("\t\t\tMATERIAL");
            sb.AppendLine("\t\t\t{");
            sb.AppendLine($"\t\t\t\tname = {materialMask}");
            sb.AppendLine("\t\t\t\tCOLOR");
            sb.AppendLine("\t\t\t\t{");
            sb.AppendLine("\t\t\t\t\tcolor = #C7C7C7");
            sb.AppendLine("\t\t\t\t}");
            sb.AppendLine("\t\t\t}");
            sb.AppendLine("\t\t}");

            // Color subtypes with MATERIAL block (required for B9PS to apply colors)
            foreach (var color in colors)
            {
                if (!color.IsUsed) continue;

                sb.AppendLine("\t\tSUBTYPE");
                sb.AppendLine("\t\t{");
                sb.AppendLine($"\t\t\tname = {color.Name}");
                sb.AppendLine($"\t\t\ttitle = {color.Title}");
                sb.AppendLine($"\t\t\tprimaryColor = {color.Color}");
                sb.AppendLine("\t\t\tMATERIAL");
                sb.AppendLine("\t\t\t{");
                sb.AppendLine($"\t\t\t\tname = {materialMask}");
                sb.AppendLine("\t\t\t\tCOLOR");
                sb.AppendLine("\t\t\t\t{");
                sb.AppendLine($"\t\t\t\t\tcolor = {color.Color}");
                sb.AppendLine("\t\t\t\t}");
                sb.AppendLine("\t\t\t}");
                sb.AppendLine("\t\t}");
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private static void GeneratePartVariantsPatch(StringBuilder sb, PartAnalyzer.PartAnalysis analysis, List<ColorEntry> colors, RepaintSettings settings)
        {
            string partName = SanitizePartName(analysis.PartName);

            sb.AppendLine($"@PART[{partName}]:FINAL");
            sb.AppendLine("{");
            sb.AppendLine("\t%SR_RepaintType = PartVariant");
            sb.AppendLine();
            sb.AppendLine("\tMODULE");
            sb.AppendLine("\t{");
            sb.AppendLine("\t\tname = ModulePartVariants");
            sb.AppendLine("\t\tuseMultipleDragCubes = false");
            sb.AppendLine();

            // Color variants with TEXTURE block (required for ModulePartVariants to apply colors)
            foreach (var color in colors)
            {
                if (!color.IsUsed) continue;

                sb.AppendLine("\t\tVARIANT");
                sb.AppendLine("\t\t{");
                sb.AppendLine($"\t\t\tname = {color.Name}");
                sb.AppendLine($"\t\t\tdisplayName = {color.Title}");
                sb.AppendLine($"\t\t\tprimaryColor = {color.Color}");
                sb.AppendLine($"\t\t\tsecondaryColor = {color.Color}");
                sb.AppendLine("\t\t\tTEXTURE");
                sb.AppendLine("\t\t\t{");
                sb.AppendLine($"\t\t\t\t_Color = {color.Color}");
                sb.AppendLine("\t\t\t}");
                sb.AppendLine("\t\t}");
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }
}
